"""商品品类分类器 — 关键词规则映射，写入 MySQL item_descriptions.category"""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import pandas as pd
from modules import db

# ════════════════════════════════════════════════════════════════════════════
# 分类规则：关键词（大写）→ 品类中文名
# 从上到下匹配，命中即停止（先细后粗）
# ════════════════════════════════════════════════════════════════════════════
RULES = [
    # ── 节日用品（圣诞 + 复活节 + 万圣节 + 情人节合并）──
    (["CHRISTMAS", "SANTA", "XMAS", "REINDEER", "SNOWMAN", "SNOW GLOBE",
      "FELTSTOCKING", "CHRISTMAS TREE", "SANTAS", "ADVENT",
      "EASTER", "BUNNY", "RABBIT", "CHICK", "SPRING CHICK", "SPRINGTIME",
      "HALLOWEEN", "SKULL", "SPIDER", "WITCH", "PUMPKIN", "BAT",
      "GHOST", "COBWEB", "TRICK OR TREAT",
      "VALENTINE", "VALENTINES", "ROMANTIC",
      "WREATH", "SLEIGH", "FESTIVE", "CELEBRATION",
      "HEN", "EGG CUP",
      "FLAG", "UNION FLAG", "ST GEORGE", "UNION JACK",
      "PATRIOTIC", "NATIONAL", "COUNTRY"], "节日用品"),

    # ── 饰品（项链/手链/耳环/戒指/胸针）──
    (["NECKLACE", "BRACELET", "EARRINGS", "EARRING", "PENDANT",
      "BROOCH", "ANKLET", "CHOKER", "BANGLE", "CUFFLINK",
      "CHAIN BRACELET", "BEAD BRACELET", "BEAD NECKLACE",
      "CRYSTAL BEAD", "GLASS BEAD", "PEARL", "GEM",
      "JEWELLERY", "JEWELRY", "LARIAT",
      "TIARA", "TIARAS", "DIADEM",
      "DIAMANTE", "RING", " BOUDICCA RING",
      "JEWEL", "JEWELLED", "ACRYLIC JEWEL",
      "ICICLE", "BEADED", "BEAD"], "饰品"),

    # ── 包袋 ──
    (["BACKPACK", "TOTE BAG", "SHOPPER BAG", "SHOPPING BAG",
      "COSMETIC BAG", "PENCIL CASE", "PURSE", "POUCH",
      "DRAWSTRING BAG", "JUTE BAG", "LUNCH BAG",
      "MESSENGER BAG", "SATCHEL", "CLUTCH", "BAG CHARM",
      "BAG", "HANDBAG", "SHOULDER BAG",
      "SHOPPER", "TOTE", "JUMBO"], "包袋/配件"),

    # ── 厨具/餐具 ──
    (["CAKE STAND", "CAKE TIN", "CAKE CASE", "CAKE SLICE",
      "MEASURING", "TEAPOT", "TEACUP", "TEATIME",
      "MUG", "CUP", "JUG", "PLATE", "DISH", "BOWL",
      "CUTLERY", "CHOPPING", "BAKING", "OVEN", "APRON",
      "KITCHEN", "SUGAR BOWL", "CREAM JUG", "MILK JUG",
      "COFFEE", "TEA TOWEL", "TEA COSY", "TEA POT",
      "TRAY", "COASTER", "PLACEMAT", "NAPKIN",
      "CAKE", "COOKIE", "CHOCOLATE", "BISCUIT",
      "EGG FRY", "FRYING", "SAUCEPAN", "CAKE DECORATION",
      "TEASPOON", "JAM POT", "JAM JAR", "BEAKER",
      "MEASURING JUG", "TABLE CLOTH", "TABLE RUNNER",
      "WATER BOTTLE", "MARMALADE", "HONEY",
      "STORAGE TIN", "STORAGE BOX", "SPICE",
      "KETTLE", "TOASTER", "COOL BAG",
      "CHOPSTICK", "CHEESE", "BUTTER",
      "LUNCH BOX", "THERMOS", "FLASK",
      "WOK", "SKILLET", "STEAMER", "STRAINER",
      "POT", "PAN", "LID", "UTENSIL",
      "PICNIC", "BARBECUE", "BBQ",
      "WHISK", "SPATULA", "LADLE", "TONG",
      "OPENER", "GRATER", "PEELER", "SCOOP",
      "FUNNEL", "COLANDER", "SIEVE",
      "ROLLING PIN", "PASTRY", "ICING",
      "TRIVET", "OVEN GLOVE", "POT HOLDER",
      "CONDIMENT", "SALT", "PEPPER",
      "OIL", "VINEGAR", "SAUCE",
      "CRUET", "DECANTER", "CARAFE",
      "TUMBLER", "GOBLET", "WINEGLASS", "WINE GLASS",
      "CHAMPAGNE", "FLUTE", "TANKARD",
      "STEIN", "PITCHER", "POPCORN",
      "SNACK", "NUTS", "NUT BOWL",
      "CANDY", "SWEET", "SWEETS",
      "BONBON", "TRUFFLE", "LOLLIPOP",
      "STRAW", "STRAWS", "BENDY STRAW",
      "SPOON", "FORK", "KNIFE", "SPORK",
      "TOASTRACK", "TOAST",
      "PUDDING", "EGG SPOON", "EGG CUP",
      "TEASPOON", "TEA SPOON", "TEA CADDY",
      "TEA FOR ONE", "TEA SET", "TEA TIME", "TEATIME",
      "WINE BOTTLE DRESSING", "WINE BOTTLE",
      "ICE CREAM", "LOLLY MAKER", "LOLLY", "POPSICLE",
      "PETIT FOUR", "PETIT", "CAMEMBERT",
      "JAM MAKING", "MARMALADE",
      "FOOD COVER", "FOOD CONTAINER",
      "EGG BASKET", "EGG HOLDER",
      "WATER BASIN", "ENAMEL",
      "PICNIC", "COOL BAG", "LUNCH",
      "BREAKFAST", "BREAKFAST SET",
      "BAKING", "ICING", "PASTRY",
      "COCKTAIL PARASOL", "COCKTAIL",
      "SWEET", "CANDY", "SNACK",
      "CHOPSTICK", "CHOP STICK",
      "TABLE", "TABLECLOTH", "TABLE CLOTH",
      "PLACEMAT", "COASTER", "NAPKIN",
      "TEAPOT", "TEACUP", "TEACUP AND SAUCER",
      "MILK BOTTLE", "MILK JUG", "CREAM JUG",
      "SUGAR BOWL", "SUGAR", "SALT AND PEPPER",
      "OIL AND VINEGAR", "CRUET", "DECANTER",
      "WATER BOTTLE", "DRINK", "DRINKS",
      "MUG", "CUP AND SAUCER", "CUP", "JUG",
      "BEER", "ALE", "CIDER",
      "WINE", "CHAMPAGNE", "COCKTAIL GLASS",
      "MEASURING", "SCALE", "WEIGH",
      "APRON", "OVEN GLOVE", "POT HOLDER", "TEA TOWEL",
      "STORAGE", "CONTAINER", "CANISTER", "JAR",
      "KETTLE", "TOASTER",
      "SQUEEZER", "JUICER", "CITRUS PRESS",
      "CAKE STAND", "CAKE TIN", "CAKE CASE",
      "TRIVET", "CHOPPING BOARD", "CUTTING BOARD",
      "ROLLING PIN", "WHISK", "SPATULA", "LADLE",
      "OPENER", "CORKSCREW", "BOTTLE OPENER",
      "GRATER", "PEELER", "SCOOP", "FUNNEL",
      "COLANDER", "SIEVE", "STRAINER",
      "POT", "PAN", "WOK", "SKILLET", "SAUCEPAN",
      "STEAMER", "LID", "UTENSIL",
      "DISH", "PLATE", "BOWL", "TRAY",
      "CUTLERY", "CHOPPING", "KITCHEN",
      "OVEN", "BAKE", "BAKING", "COOKIE", "BISCUIT",
      "CAKE", "CHOCOLATE", "CHEESE", "BUTTER",
      "THERMOS", "FLASK", "VACUUM",
      "PICNIC", "BARBECUE", "BBQ"], "厨具/餐具"),

    # ── 蜡烛/烛台 ──
    (["CANDLE", "T-LIGHT", "TEALIGHT", "TEALIGHTS",
      "CANDELABRA", "CANDLESTICK", "WAX",
      "LANTERN", "HURRICANE LAMP"], "蜡烛/香薰"),

    # ── 花园/户外 ──
    (["GARDEN", "FLOWER", "PLANT", "SEED", "BULB",
      "BIRD HOUSE", "BIRDHOUSE", "BIRD TABLE", "BIRD FEEDER",
      "BUTTERFLY", "DRAGONFLY", "LADYBIRD", "BEE",
      "WATERING", "TROWEL", "WEED", "GARDENING",
      "ARTIFICIAL FLOWER", "DRIED FLOWER",
      "HANGING BASKET", "WINDOW BOX", "PLANTER",
      "HAMMOCK", "TOADSTOOL", "MUSHROOM",
      "FLYING DUCK", "WILDLIFE", "SQUIRREL",
      "HEDGEHOG", "ROBIN", "OWL", "FOX",
      "PINE CONE", "Pinecone", "PINECONE",
      "EUCALYPTUS", "LAVENDER", "ROSEMARY",
      "HERB", "BOTANICAL", "LEAF", "IVY",
      "FERN", "PALM", "CACTUS", "SUCCULENT",
      "TERRACOTTA", "STONE", "PEBBLE",
      "SOLAR LIGHT", "GARDEN LIGHT",
      "WHEELBARROW", "WELLINGTON"], "花园/户外"),

    # ── 文具/办公 ──
    (["NOTEBOOK", "NOTEPAD", "PENCIL", "PEN", "STICKER",
      "STICKERS", "STICKY", "CARD", "WRITING",
      "STATIONERY", "SCISSORS", "RULER", "ERASER",
      "DIARY", "JOURNAL", "SKETCHBOOK", "ALBUM",
      "BOOKMARK", "MAGNETIC", "MAGNETS",
      "TAPE DISPENSER", "PAPERWEIGHT",
      "GIFT TAG", "GIFT WRAP", "GIFT BAG",
      "GREETING CARD", "POSTCARD", "ENVELOPE",
      "WRAP", "PAPER", "PAPER PAD", "PAPER SET",
      "CALCULATOR", "SEWING", "KNITTING",
      "MEMO", "PUSH PIN", "DRAWING PIN",
      "PAPERCLIP", "PAPER CLIP", "CLIP",
      "PIN BOARD", "WHITEBOARD", "CHALKBOARD",
      "CALENDAR", "PLANNER", "ORGANISER",
      "ADDRESS BOOK", "PHOTO ALBUM", "SCRAPBOOK",
      "STAMP", "INK PAD", "INK", "PAINT",
      "BRUSH", "PALETTE", "EASEL",
      "CRAFT", "DECOUPAGE", "STENCIL",
      "GLITTER", "BEAD", "SEQUIN",
      "EMBROIDERY", "CROCHET", "CROSS STITCH",
      "NEEDLE", "THREAD", "YARN", "WOOL",
      "POM POM", "FEATHER", "PIPE CLEANER",
      "GOOGLY EYE", "WIGGLE EYE",
      "TAPE", "TAPE MEASURE", "BOOKCOVER", "BOOK COVER",
      "POCKET BOOK", "EXERCISE BOOK", "NOTE BOOK",
      "CHALK", "CHALKBOARD", "BLACK BOARD",
      "HOLE PUNCH", "PUNCH",
      "SCISSOR", "SCISSORS", "FOLDING SCISSOR",
      "BUTTON", "BUTTON BOX", "PATCH",
      "IRON ON", "SEWING", "NEEDLE",
      "PAPERWEIGHT", "P'WEIGHT",
      "JIGSAW", "MINI JIGSAW", "PUZZLE",
      "BOARD GAME", "NAUGHTS", "CROSSES",
      "SNAKES", "LADDERS", "PLAYING CARD",
      "SCRAP BOOK", "SCRAPBOOK",
      "TREASURE BOOK", "BOOK BOX",
      "ABC", "ALPHABET", "NUMBER",
      "RETRO NOTE", "SCHOOL", "BUNDLE OF",
      "CHILDREN", "CHILDS", "BABY",
      "GIFT SET", "GIFT BOX", "GIFT BAG",
      "CRACKER", "MINI CRACKER",
      "HARMONICA", "MUSICAL", "MUSIC",
      "MATCHES", "MATCHBOX", "GIANT TUBE MATCH", "CIGAR BOX MATCH",
      "LIP GLOSS", "MAKEUP", "COSMETIC",
      "FIRST AID", "PHARMACIE", "MEDICAL",
      "SCREWDRIVER", "SPIRIT LEVEL", "TOOL",
      "FLY SWAT", "FLYSWAT",
      "BICYCLE BELL", "CHROME BELL",
      "MINI CASE", "MINI CASES",
      "TREASURE TIN", "KNICK KNACK", "SET OF",
      "METAL BOX", "GREEN METAL", "RED METAL",
      "RETRO RADIO", "RADIO",
      "SMALL POP BOX", "POP BOX",
      "HIGH RESOLUTION", "PACKING CHARGE"], "文具/办公"),

    # ── 家居装饰 ──
    (["CUSHION", "PILLOW", "THROW", "RUG", "DOORMAT",
      "CLOCK", "MIRROR", "FRAME", "PHOTO FRAME",
      "WALL ART", "WALL DECOR", "WALL HANGING",
      "STORAGE", "DRAWER", "SHELF", "HOOK",
      "VASE", "ORNAMENT", "FIGURINE", "STATUE",
      "SNOW GLOBE", "MUSIC BOX",
      "DOORSTOP", "DOOR STOP", "KEY CABINET",
      "CURTAIN", "BLIND", "LIGHT SHADE",
      "HOME", "DECORATION", "HANGING DECORATION",
      "WOODEN", "CERAMIC", "GLASS", "CRYSTAL",
      "METAL SIGN", "WOOD SIGN", "WOODEN SIGN",
      "SIGN", "PLAQUE", "HANGING SIGN",
      "WASTE BIN", "WASTE PAPER", "BIN",
      "TRELLIS", "WICKER", "RUSTIC",
      "FILLER PAD", "POLYESTER", "CUSHION PAD",
      "DOOR HANGER", "ROOM SPRAY",
      "DIFFUSER", "REED", "POTPOURRI",
      "INCENSE", "OIL BURNER", "AROMATHERAPY",
      "CHIME", "WINDCHIME", "DREAMCATCHER",
      "MACRAME", "WALL HANGING", "TAPESTRY",
      "BUNTING", "BANNER", "PENNANT",
      "GARLAND", "WREATH", "SWAG",
      "HEART", "STAR", "LOVE",
      "PHOTO", "PICTURE", "CANVAS",
      "DRAWER KNOB", "DOOR KNOB", "HANDLE",
      "LETTER RACK", "MAGAZINE RACK",
      "UMBRELLA STAND", "COAT RACK",
      "SHOE RACK", "SHOE STORAGE",
      "LAUNDRY", "IRONING", "CLOTHES AIRER",
      "STEP LADDER", "STOOL", "CHAIR",
      "FURNITURE", "CABINET", "CHEST",
      "BLANKET", "BEDDING", "LINEN",
      "TOWEL", "BATH", "SOAP",
      "TOILET", "BATHROOM", "SHOWER",
      "LAMP", "LAMPSHADE", "CHANDELIER", "LIGHT",
      "SHADE", "BULB", "LANTERN", "TORCH",
      "TABLE LIGHT", "NIGHT LIGHT", "FAIRY LIGHT",
      "LIGHT CHAIN", "LIGHTING", "LED",
      "MOBILE", "WINDMILL", "WINDSOCK",
      "KEEPSAKE", "TREASURE", "BOOK BOX", "TREASURE BOOK",
      "WALL TIDY", "CD WALL", "SHELVING",
      "MAT", "RECYCLED MAT", "ACAPULCO", "RUG",
      "POUFFE", "FOOTSTOOL", "OTTOMAN",
      "CHEST", "BOX", "TIN", "TRINKET",
      "HANGING BOTTLE", "MINI BOTTLE", "MILK BOTTLE",
      "ALPHABET BLOCK", "JIGSAW BLOCK",
      "WOOD LETTER", "WOODEN LETTER",
      "NUMBER TILE", "SLATE TILE",
      "IRONING", "LAUNDRY", "CLOTHES",
      "SHOE", "SHOE RACK", "STEP LADDER",
      "COAT RACK", "HOOK", "RAIL",
      "BASKET", "FRENCH STYLE BASKET",
      "FIRE BUCKET", "ENAMEL FIRE",
      "WALL THERMOMETER", "THERMOMETER",
      "CLAM SHELL", "SHELL", "SEASHELL",
      "PORCELAIN", "FIGURINE", "STATUE",
      "FRIDGE MAGNET", "MAGNET", "REFRIGERATOR",
      "BIRD", "HANGING BIRD", "WOOD BIRD",
      "METAL CAT", "CAT", "DOG",
      "SCREEN", "BIRD CEATURE",
      "FLAG", "BANNER", "PENNANT",
      "HANGING BOTTLE", "COLOURED BOTTLE",
      "PRINT", "PICTURE", "CANVAS",
      "GEISHA", "ORIENTAL", "CHINESE",
      "SNOWFLAKE", "FROSTED",
      "SILICON", "ACRYLIC"], "家居装饰"),

    # ── 玩具/派对 ──
    (["DOLL", "PUZZLE", "DOMINO", "DICE", "PLAYING",
      "GAME", "TOY", "YO-YO", "KITE", "SPINNING",
      "BUBBLE", "BALLOON", "PARTY", "BUNTING",
      "GARLAND", "CONFETTI", "PINATA",
      "CHILDREN", "KIDS", "CRAYON",
      "RUBBER", "INFLATABLE", "BOUNCY",
      "BOOM BOX", "SPEAKER", "SOUND",
      "PLASTERS", "CREEPY", "CRAWLIE",
      "COCKTAIL SWORD", "SWORD",
      "BEACH BALL", "FRISBEE", "SKIPPING",
      "JOKE", "MAGIC", "TRICK",
      "PAINT YOUR OWN", "MAKE YOUR OWN",
      "MODEL", "KIT", "BUILD",
      "FELT", "WOODEN TOY", "WOODEN ANIMAL",
      "TRAIN", "CAR", "BUS", "TRACTOR", "FIRE ENGINE",
      "SOLDIER", "KNIGHT", "PIRATE", "PRINCESS",
      "FAIRY", "UNICORN", "MERMAID", "DRAGON",
      "DINOSAUR", "ANIMAL", "ZOO",
      "HELICOPTER", "SPACEBOY", "SPACE BOY", "SPACE CADET",
      "SPACE FROG", "SNAKE SET", "SNAKE  SET",
      "FROG SOCK", "SOCK PUPPET", "PUPPET",
      "TEDDY", "GNOME", "DOLL", "DOLLS",
      "BABY MOUSE", "MOUSE",
      "SANDCASTLE", "BEACH SPADE", "SEASIDE BUCKET",
      "SEASIDE FLYING DISC", "FLYING DISC",
      "ALPHABET BLOCK", "JIGSAW BLOCK", "BOX OF VINTAGE",
      "BREAKFAST SET", "GIFT SET",
      "ICE CREAM", "POPSICLE", "ICE LOLLY",
      "CANDY", "SWEET", "LOLLIPOP",
      "LIP GLOSS", "LIP BALM", "MAKE UP",
      "GLOW", "GLOWING", "GLOW IN",
      "WINDMILL", "WINDSOCK", "KITE",
      "BUBBLE", "BALLOON", "PARTY",
      "RATTLE SNAKE", "RATTLESNAKE",
      "MONSTER", "SPACEBOY", "SPACE BOY",
      "PLAYHOUSE", "DOLLHOUSE", "DOLLS HOUSE",
      "GEISHA", "FIGURINE",
      "STICKER", "STICKY"], "玩具/派对"),

    # ── 服装/配饰 ──
    (["SCARF", "SHAWL", "GLOVES", "MITTS", "HAT",
      "UMBRELLA", "SUNGLASSES", "BELT", "TIE",
      "KEYRING", "KEY RING", "KEYCHAIN", "KEY-CHAIN", "KEY FOB",
      "KEY CHAIN", "RASTA KEY",
      "LUGGAGE", "SUITCASE", "TRAVEL",
      "FABRIC", "RIBBON", "LACE", "COTTON",
      "TEXTILE", "KNITTED", "CROCHET",
      "APRON", "TISSUE", "TISSUES",
      "PONCHO", "RAINCOAT", "JACKET",
      "FAN", "SILK FAN", "HAND FAN",
      "PURSE", "WALLET", "COIN PURSE",
      "PASSPORT", "TRAVEL POUCH",
      "MAKEUP BAG", "TOILETRY BAG",
      "COSMETIC", "COMPACT", "MIRROR COMPACT",
      "HAIR", "HEADBAND", "HAIRBAND",
      "BROOCH", "BADGE", "PIN",
      "SUSPENDER", "BRACES", "HANKIE",
      "HANDKERCHIEF", "BANDANA",
      "SLIPPER", "SHOES", "SLIPPER SHOES",
      "SKIRT", "GRASS SKIRT", "HAWAIIAN",
      "SOCK", "AFGHAN SLIPPER",
      "EAR MUFF", "EARMUFF", "HEADPHONE",
      "HAND WARMER",
      "SOMBRERO", "HAT",
      "PARASOL", "UMBRELLA",
      "PATCH", "IRON ON PATCH",
      "EMBROIDERED", "QUILT",
      "DRESSING", "DRESS", "COSTUME",
      "SUNGLASS", "GLASSES", "SPECTACLE",
      "WATCH", "WRISTBAND", "BRACELET",
      "WALLET", "COIN PURSE", "CARD HOLDER"], "服装/配饰"),
]


def classify(desc: str) -> str:
    """根据英文描述文字返回品类中文名"""
    d = desc.upper()
    for keywords, category in RULES:
        for kw in keywords:
            if kw in d:
                return category
    return "其他"


# ════════════════════════════════════════════════════════════════════════════
def main():
    print("读取 item_descriptions...")
    cn = db.read_table("item_descriptions")
    print(f"  {len(cn)} 条记录")

    print("分类中...")
    cn["category"] = cn["Description"].apply(classify)

    # 统计
    print("\n品类分布:")
    for cat, cnt in cn["category"].value_counts().items():
        print(f"  {cnt:5d}  {cat}")

    # 写入数据库
    print("\n写入 MySQL...")
    eng = db.get_engine()
    with eng.connect() as conn:
        for _, row in cn.iterrows():
            conn.execute(
                db.text("UPDATE item_descriptions SET category = :cat WHERE StockCode = :sc"),
                {"cat": row["category"], "sc": row["StockCode"]},
            )
        conn.commit()
    print("完成!")


if __name__ == "__main__":
    main()
